Traceback (most recent call last):
  File "/data/zhanglab/afeeney/python3/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/data/zhanglab/afeeney/python/Python-3.5.0/Lib/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/data/zhanglab/afeeney/python3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid reduction dimension 1 for input with 1 dimensions. for 'Mean' (op: 'Mean') with input shapes: [2], [] and with computed input tensors: input[1] = <1>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/afeeney/PoseNetwork/src/main.py", line 182, in <module>
    main()
  File "/home/afeeney/PoseNetwork/src/main.py", line 46, in main
    decode_dual_stream(end_points, lr=1e-4)
  File "/home/afeeney/PoseNetwork/src/net.py", line 116, in decode_dual_stream
    model['acc'] = tf.reduce_mean(distance, axis=1)
  File "/data/zhanglab/afeeney/python3/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1355, in reduce_mean
    name=name)
  File "/data/zhanglab/afeeney/python3/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1290, in _mean
    keep_dims=keep_dims, name=name)
  File "/data/zhanglab/afeeney/python3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/data/zhanglab/afeeney/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/data/zhanglab/afeeney/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/data/zhanglab/afeeney/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/data/zhanglab/afeeney/python3/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/data/zhanglab/afeeney/python3/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Invalid reduction dimension 1 for input with 1 dimensions. for 'Mean' (op: 'Mean') with input shapes: [2], [] and with computed input tensors: input[1] = <1>.
